### ISSUE TITLE
Update not firing if move also occurs

### ISSUE THREAD

**Issue by tkrajacic** [matteorattotti/MRTFetchedResultsController#2]
I think the logic for update and move delegate calls is not entirely correct.

If an object changes places because of updates of one of the sorting criteria properties (think `lastname` in a phonebook for example) the update delegate method needs to be fired in addition to the move notification. In fact, the update notification should always be sent for `updated` objects.

So `// UPDATED OR MOVED` should actually be `// UPDATED AND MAYBE EVEN MOVED`.

**Comment by matteorattotti** [comment]
Update should not fire when a move occurs, a move is already an update as a change of order imply something has changed in the model (the `lastname` in your example).

MRTFetchedResultsController is modelled after NSFetchedResultsController and I'm trying to keep the behaviours as close as possible to the Apple class.

**Comment by tkrajacic** [comment]
Mhm, according to the sample code in the docs at https://developer.apple.com/reference/coredata/nsfetchedresultscontrollerdelegate
Apple doesn't suggests calling `configureCell` from a `move` notification. This makes me think that they do fire update events for cells that have changed content regardless if they have moved. I might be wrong though, as I have not tried it.

**Comment by matteorattotti** [comment]
I'm using another project setup just for testing the `NSFetchedResultsController` and I can confirm that only the `move` is called (even if you change at the same time other properties that doesn't affect the order).

Just for safety try to test it by yourself and let me know if you can simulate something different, I'll leave the issue open for now.

**Comment by tkrajacic** [comment]
I just tested this myself, and you are absolutely right. NSFetchedResultsController only sends one or the other.

I did miss the fact that Apple's sample code uses `deleteRow` and `insertRow` instead of the (in my humble opinion) more obvious `moveRow` method. The latter will not redraw while the first way of doing things of course will.

Sorry for the confusion.

**Comment by matteorattotti** [comment]
No problem, it's good to have a second opinion :)

I'll mark this issue close.
