### ISSUE TITLE
Logic for updated and moved doesn't work for incremental updates

### ISSUE THREAD

**Issue by tkrajacic** [matteorattotti/MRTFetchedResultsController#3]
The condition `if (index == newIndex && progressiveIndex == newIndex)` to filter out moves does not make sense when using progressive indices. Then it is not relevant if the index == newIndex, but rather just if the progressiveIndex == newIndex. So this condition always evaluates to false and a move is erroneously reported (You see a lot of moves where `from` and `to` are the same currently).

I guess the conditions need to be split up into separate clauses for using progressive indices and when you are not using them.

**Comment by matteorattotti** [comment]
Ah yes, that was already fixed in the `develop` branch, I forgot to merge it in `master` (just did it).

Thanks for reporting it.
